"""Generate small, well-formed (and deliberately malformed) package files for tests.

Nothing here touches the host: every builder writes into a caller-provided directory.
"""

from __future__ import annotations

import io
import shutil
import struct
import subprocess
import tarfile
from pathlib import Path


# -- Arch packages --------------------------------------------------------------------------------
def build_pkg(dest: Path, *, name="hello", version="1.0-1", arch="x86_64", depends=("glibc",),
              install_script: str | None = None, compression="zst", extra_pkginfo: str = "") -> Path:
    pkginfo = (
        f"# Generated by makepkg\npkgname = {name}\npkgbase = {name}\npkgver = {version}\n"
        f"pkgdesc = Test package {name}\nurl = https://example.invalid\nbuilddate = 1700000000\n"
        f"packager = Test <test@example.invalid>\nsize = 12345\narch = {arch}\nlicense = MIT\n"
        + "".join(f"depend = {d}\n" for d in depends)
        + "optdepend = foo: optional foo support\nprovides = libhello.so=1-64\n"
        + extra_pkginfo
    )
    path = dest / f"{name}-{version}-{arch}.pkg.tar.{compression}"
    mode = f"w:{compression}" if compression else "w"
    with tarfile.open(path, mode) as tar:
        members = [(".BUILDINFO", b"format = 2\n"), (".MTREE", b"#mtree\n"), (".PKGINFO", pkginfo.encode())]
        if install_script is not None:
            members.append((".INSTALL", install_script.encode()))
        members.append(("usr/bin/hello", b"#!/bin/sh\necho hello\n"))
        for member_name, data in members:
            info = tarfile.TarInfo(member_name)
            info.size = len(data)
            tar.addfile(info, io.BytesIO(data))
    return path


# -- Debian packages ------------------------------------------------------------------------------
def _ar(members: list[tuple[str, bytes]]) -> bytes:
    out = bytearray(b"!<arch>\n")
    for name, data in members:
        header = (
            name.ljust(16)[:16] + "0".ljust(12) + "0".ljust(6) + "0".ljust(6) + "100644".ljust(8)
            + str(len(data)).ljust(10)
        ).encode("ascii") + b"`\n"
        out += header + data
        if len(data) % 2:
            out += b"\n"
    return bytes(out)


def _tar_bytes(files: dict[str, bytes], mode: str) -> bytes:
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode=mode) as tar:
        for name, data in files.items():
            info = tarfile.TarInfo(name)
            info.size = len(data)
            info.mode = 0o755 if name.endswith(("inst", "rm")) or data.startswith(b"#!") else 0o644
            tar.addfile(info, io.BytesIO(data))
    return buf.getvalue()


def build_deb(dest: Path, *, name="hello", version="1.2.3-1", arch="amd64",
              depends="libc6 (>= 2.34), libssl3 | libssl1.1", scripts: dict[str, str] | None = None,
              control_extra: str = "", files: dict[str, bytes] | None = None) -> Path:
    control = (
        f"Package: {name}\nVersion: {version}\nArchitecture: {arch}\nMaintainer: Test <t@example.invalid>\n"
        f"Installed-Size: 42\nDepends: {depends}\nRecommends: hello-doc\nSection: utils\n"
        f"Homepage: https://example.invalid\nDescription: Test package\n second line of description\n"
        + control_extra
    )
    control_files = {"./control": control.encode()}
    for sname, body in (scripts or {}).items():
        control_files[f"./{sname}"] = body.encode()
    control_tar = _tar_bytes(control_files, "w:xz")
    data_tar = _tar_bytes({f"./{k.lstrip('./')}": v for k, v in (files or {"usr/bin/hello": b"#!/bin/sh\n"}).items()},
                          "w:gz")
    path = dest / f"{name}_{version}_{arch}.deb"
    path.write_bytes(_ar([("debian-binary", b"2.0\n"), ("control.tar.xz", control_tar),
                          ("data.tar.gz", data_tar)]))
    return path


# -- RPM packages ---------------------------------------------------------------------------------
STRING, INT32, STRING_ARRAY, BIN = 6, 4, 8, 7


def _rpm_header(entries: list[tuple[int, int, object]]) -> bytes:
    index, store = bytearray(), bytearray()
    for tag, typ, value in entries:
        if typ == INT32:
            while len(store) % 4:
                store += b"\0"
            values = value if isinstance(value, list) else [value]
            offset, count = len(store), len(values)
            store += struct.pack(f">{count}I", *values)
        elif typ == STRING:
            offset, count = len(store), 1
            store += str(value).encode() + b"\0"
        elif typ in (STRING_ARRAY, 9):  # 9 = I18NSTRING
            offset, count = len(store), len(value)  # type: ignore[arg-type]
            for item in value:  # type: ignore[union-attr]
                store += str(item).encode() + b"\0"
        else:
            offset, count = len(store), len(value)  # type: ignore[arg-type]
            store += bytes(value)  # type: ignore[arg-type]
        index += struct.pack(">iIiI", tag, typ, offset, count)
    return b"\x8e\xad\xe8\x01\0\0\0\0" + struct.pack(">II", len(entries), len(store)) + bytes(index) + bytes(store)


def build_rpm(dest: Path, *, name="hello", version="1.2.3", release="1", arch="x86_64",
              requires=("libc.so.6()(64bit)", "rpmlib(PayloadIsZstd)", "/bin/sh"),
              postin: str | None = "systemctl enable hello.service || :", signed=False,
              files: dict[str, bytes] | None = None, extra: tuple = ()) -> Path:
    lead = b"\xed\xab\xee\xdb\x03\x00" + struct.pack(">hh", 0, 1) + name.encode().ljust(66, b"\0")[:66] \
        + struct.pack(">hh", 1, 5) + b"\0" * 16
    sig_entries: list[tuple[int, int, object]] = [(1000, INT32, [123])]
    if signed:
        sig_entries.append((268, BIN, b"\x89" * 32))
    sig = _rpm_header(sig_entries)
    sig += b"\0" * ((8 - len(sig) % 8) % 8)
    flags = [0x1000000 if r.startswith("rpmlib(") else 0 for r in requires]
    entries: list[tuple[int, int, object]] = [
        (1000, STRING, name), (1001, STRING, version), (1002, STRING, release),
        (1004, STRING, "Test package"), (1009, INT32, [4096]), (1014, STRING, "MIT"),
        (1022, STRING, arch), (1049, STRING_ARRAY, list(requires)), (1048, INT32, flags),
        (1050, STRING_ARRAY, [""] * len(requires)), (1047, STRING_ARRAY, [name]),
        (1124, STRING, "cpio"), (1125, STRING, "zstd"),
    ]
    if postin is not None:
        entries += [(1024, STRING, postin), (1086, STRING, "/bin/sh")]
    entries += list(extra)  # (tag, type, value) triples: e.g. a %posttrans scriptlet and its program
    path = dest / f"{name}-{version}-{release}.{arch}.rpm"
    path.write_bytes(lead + sig + _rpm_header(entries) + (_cpio_zst(dest, files) if files else b"payload"))
    return path


def _cpio_zst(dest: Path, files: dict[str, bytes]) -> bytes:
    """A real RPM payload: a newc cpio archive, zstd-compressed."""
    import tempfile

    with tempfile.TemporaryDirectory(dir=dest) as tmp:
        for rel, data in files.items():
            f = Path(tmp) / rel.lstrip("./")
            f.parent.mkdir(parents=True, exist_ok=True)
            f.write_bytes(data)
            f.chmod(0o755 if data.startswith(b"#!") else 0o644)
        cpio = subprocess.run(["bsdtar", "--format", "newc", "-cf", "-", "-C", tmp, "."], check=True,
                              capture_output=True).stdout
    return subprocess.run(["zstd", "-q", "-c"], input=cpio, check=True, capture_output=True).stdout


# -- AppImages ------------------------------------------------------------------------------------
DESKTOP = """[Desktop Entry]
Type=Application
Name=Hello World
Comment=Says hello
Exec=hello %U
Icon=hello
Categories=Utility;
MimeType=x-scheme-handler/hello;text/plain;
X-AppImage-Version=2.5.0
"""
APPSTREAM = """<?xml version="1.0" encoding="UTF-8"?>
<component type="desktop-application">
  <id>org.example.Hello</id>
  <name>Hello World</name>
  <summary>Says hello politely</summary>
  <developer id="org.example"><name>Example Corp</name></developer>
  <project_license>MIT</project_license>
  <releases><release version="2.5.0" date="2026-01-01"/></releases>
</component>
"""
PNG_1PX = bytes.fromhex(
    "89504e470d0a1a0a0000000d4948445200000001000000010806000000"
    "1f15c4890000000d49444154789c6360000002000154a24f5d0000000049454e44ae426082"
)


def _elf_stub(update_info: str, signed: bool) -> bytes:
    shstrtab = b"\0.upd_info\0.sha256_sig\0.sig_key\0.shstrtab\0"
    upd = update_info.encode().ljust(1024, b"\0")
    sig = (b"-----BEGIN PGP SIGNATURE-----" if signed else b"").ljust(1024, b"\0")
    key = (b"-----BEGIN PGP PUBLIC KEY BLOCK-----" if signed else b"").ljust(8192, b"\0")
    data = bytearray(b"\0" * 64)
    offsets = {}
    for label, blob in (("upd", upd), ("sig", sig), ("key", key), ("str", shstrtab)):
        offsets[label] = len(data)
        data += blob
    while len(data) % 8:
        data += b"\0"
    shoff = len(data)

    def sh(name_off, sh_type, off, size):
        return struct.pack("<IIQQQQIIQQ", name_off, sh_type, 0, 0, off, size, 0, 0, 1, 0)

    table = sh(0, 0, 0, 0)
    table += sh(1, 7, offsets["upd"], len(upd))
    table += sh(11, 7, offsets["sig"], len(sig))
    table += sh(23, 7, offsets["key"], len(key))
    table += sh(32, 3, offsets["str"], len(shstrtab))
    ident = b"\x7fELF" + bytes([2, 1, 1, 0]) + b"AI\x02" + b"\0" * 5
    header = ident + struct.pack("<HHIQQQIHHHHHH", 2, 0x3E, 1, 0, 0, shoff, 0, 64, 0, 0, 64, 5, 4)
    data[:64] = header
    return bytes(data) + table


def build_appimage(dest: Path, *, update_info="zsync|https://example.invalid/Hello.AppImage.zsync",
                   signed=False, with_squashfs: bool | None = None, desktop: str = DESKTOP,
                   escape_symlink: bool = False, version: str = "2.5.0", app_id: str = "org.example.Hello") -> Path:
    """Create a fake type-2 AppImage. With mksquashfs available the payload is a real squashfs image."""
    desktop = desktop.replace("X-AppImage-Version=2.5.0", f"X-AppImage-Version={version}")
    appstream = APPSTREAM.replace('version="2.5.0"', f'version="{version}"').replace("org.example.Hello", app_id)
    path = dest / "Hello-x86_64.AppImage"
    runtime = _elf_stub(update_info, signed)
    mksquashfs = shutil.which("mksquashfs")
    if with_squashfs is None:
        with_squashfs = mksquashfs is not None
    if with_squashfs:
        if mksquashfs is None:
            raise RuntimeError("mksquashfs not available")
        root = dest / "appdir"
        (root / "usr/share/metainfo").mkdir(parents=True)
        (root / "usr/share/applications").mkdir(parents=True)
        (root / "usr/share/applications/hello.desktop").write_text(desktop)
        if escape_symlink:
            (root / "hello.desktop").symlink_to("/etc/passwd")
        else:
            (root / "hello.desktop").symlink_to("usr/share/applications/hello.desktop")
        (root / "hello.png").write_bytes(PNG_1PX)
        (root / ".DirIcon").symlink_to("hello.png")
        (root / f"usr/share/metainfo/{app_id}.appdata.xml").write_text(appstream)
        (root / "AppRun").write_text("#!/bin/sh\nexit 0\n")
        img = dest / "payload.squashfs"
        subprocess.run([mksquashfs, str(root), str(img), "-quiet", "-noappend", "-all-root"], check=True)
        payload = img.read_bytes()
    else:
        payload = b"hsqs" + b"\0" * 252
    path.write_bytes(runtime + payload)
    path.chmod(0o755)
    return path


# -- Flatpak --------------------------------------------------------------------------------------
FLATPAKREF = """[Flatpak Ref]
Title=Example App
Name=org.example.App
Branch=stable
Url=https://dl.example.invalid/repo/
SuggestRemoteName=example
GPGKey=mQENBGRmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
RuntimeRepo=https://dl.example.invalid/example.flatpakrepo
IsRuntime=false
"""


def build_flatpak_bundle(dest: Path, *, runtime="org.cygnus.TestPlatform/x86_64/1",
                         origin_url: str | None = None) -> Path:
    """Build a real single-file bundle from a hand-made OSTree commit (no SDK, no installation)."""
    ostree, flatpak = shutil.which("ostree"), shutil.which("flatpak")
    if not ostree or not flatpak:
        raise RuntimeError("ostree and flatpak are required")
    app = dest / "app"
    (app / "files/bin").mkdir(parents=True)
    metadata = (f"[Application]\nname=org.cygnus.TestApp\nruntime={runtime}\n"
                "sdk=org.cygnus.TestSdk/x86_64/1\ncommand=testapp\n\n[Context]\nshared=network;\n")
    (app / "metadata").write_text(metadata)
    exe = app / "files/bin/testapp"
    exe.write_text("#!/bin/sh\necho hi\n")
    exe.chmod(0o755)
    repo = dest / "repo"
    subprocess.run([ostree, "init", "--mode=archive-z2", f"--repo={repo}"], check=True)
    subprocess.run([ostree, "commit", f"--repo={repo}", "--branch=app/org.cygnus.TestApp/x86_64/stable",
                    f"--tree=dir={app}", "--subject=test", f"--add-metadata-string=xa.metadata={metadata}"],
                   check=True, capture_output=True)
    out = dest / "test.flatpak"
    argv = [flatpak, "build-bundle", str(repo), str(out), "org.cygnus.TestApp", "stable",
            "--runtime-repo=https://example.invalid/test.flatpakrepo"]
    if origin_url:
        argv.append(f"--repo-url={origin_url}")
    env = {"FLATPAK_USER_DIR": str(dest / "fp-user"), "PATH": "/usr/bin:/bin", "HOME": str(dest)}
    subprocess.run(argv, check=True, capture_output=True, env=env)
    return out


# -- Flatpak repositories ---------------------------------------------------------------------------
class GpgTestKey:
    """A throwaway signing key in its own GnuPG home (never the user's ~/.gnupg); use as a context
    manager so the agent it starts is always stopped."""

    def __init__(self, root: Path):
        self.home = root / "gnupg"
        self.home.mkdir(mode=0o700, parents=True)
        self._gpg = ["gpg", "--homedir", str(self.home), "--batch", "--pinentry-mode", "loopback", "--passphrase", ""]
        subprocess.run(self._gpg + ["--quick-gen-key", "Cygnus Test <test@example.invalid>", "ed25519", "sign",
                                    "never"], check=True, capture_output=True)
        colons = subprocess.run(self._gpg + ["--list-keys", "--with-colons"], capture_output=True, text=True,
                                check=True).stdout
        self.keyid = next(l.split(":")[9] for l in colons.splitlines() if l.startswith("fpr:"))
        self.public = root / "key.gpg"
        self.public.write_bytes(subprocess.run(self._gpg + ["--export", self.keyid], capture_output=True,
                                               check=True).stdout)

    def sign_args(self, prefix: str = "--gpg-") -> list[str]:
        return [f"{prefix}sign={self.keyid}", f"{prefix}homedir={self.home}"]

    def __enter__(self) -> GpgTestKey:
        return self

    def __exit__(self, *exc) -> None:
        subprocess.run(["gpgconf", "--homedir", str(self.home), "--kill", "all"], capture_output=True)


def build_flatpak_repo(root: Path, runtimes: dict[str, str | None], key: GpgTestKey | None = None,
                       apps: dict[str, str] | None = None, extensions: dict[str, str] | None = None) -> Path:
    """An archive repository holding empty runtimes, {"name/arch/branch": eol-reason-or-None}, and
    tiny apps, {"app.id": "runtime/arch/branch"} (branch "stable")."""
    repo = root / "repo"
    repo.mkdir(parents=True)
    subprocess.run(["ostree", "init", "--mode=archive-z2", f"--repo={repo}"], check=True)
    for runtime, eol in runtimes.items():
        tree = root / "trees" / runtime.replace("/", "_")
        (tree / "files").mkdir(parents=True)
        meta = f"[Runtime]\nname={runtime.split('/')[0]}\nruntime={runtime}\n"
        ext = (extensions or {}).get(runtime)  # an extension Flatpak installs along with the runtime
        if ext:
            meta += f"\n[Extension {ext}]\ndirectory=ext\nversion={runtime.split('/')[2]}\nautodelete=true\n"
        (tree / "metadata").write_text(meta)
        argv = ["ostree", "commit", f"--repo={repo}", f"--branch=runtime/{runtime}", f"--tree=dir={tree}",
                "--subject=test", f"--add-metadata-string=xa.metadata={meta}"]
        if eol:
            argv.append(f"--add-metadata-string=ostree.endoflife={eol}")
        subprocess.run(argv + (key.sign_args() if key else []), check=True, capture_output=True)
    for app_id, runtime in (apps or {}).items():
        tree = root / "trees" / app_id
        (tree / "files/bin").mkdir(parents=True)
        exe = tree / "files/bin/testapp"
        exe.write_text("#!/bin/sh\necho hi\n")
        exe.chmod(0o755)
        meta = f"[Application]\nname={app_id}\nruntime={runtime}\ncommand=testapp\n\n[Context]\nshared=network;\n"
        (tree / "metadata").write_text(meta)
        subprocess.run(["ostree", "commit", f"--repo={repo}", f"--branch=app/{app_id}/x86_64/stable",
                        f"--tree=dir={tree}", "--subject=test", f"--add-metadata-string=xa.metadata={meta}",
                        *(key.sign_args() if key else [])], check=True, capture_output=True)
    subprocess.run(["flatpak", "build-update-repo", *(key.sign_args() if key else []), str(repo)],
                   check=True, capture_output=True,
                   env={"FLATPAK_USER_DIR": str(root / "unused"), "PATH": "/usr/bin:/bin", "HOME": str(root)})
    return repo


def add_ostree_remote(installation_dir: Path, name: str, repo: Path, key: GpgTestKey | None) -> None:
    """Configure a remote directly in an installation's repository, the way a system administrator's
    `flatpak remote-add` leaves it (keyring stored as <repo>/<name>.trustedkeys.gpg)."""
    target = installation_dir / "repo"
    if not target.exists():
        installation_dir.mkdir(parents=True, exist_ok=True)
        subprocess.run(["ostree", "init", "--mode=bare-user-only", f"--repo={target}"], check=True)
    trust = [f"--gpg-import={key.public}"] if key else ["--no-gpg-verify"]
    subprocess.run(["ostree", "remote", "add", f"--repo={target}", *trust, name, f"file://{repo}"],
                   check=True, capture_output=True)
